"use client";

import { FileText, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";

/**
 * Terms of Use page.
 * Styled to match the modern dashboard design system.
 */
export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background py-20 px-4 sm:px-6 relative overflow-hidden">
      <div className="absolute inset-0 bg-grid-cyber opacity-[0.03] pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-secondary/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-2xl mx-auto relative z-10 space-y-8">
        <div className="bg-card border border-border rounded-2xl p-8 sm:p-12 shadow-lg">
          <div className="flex items-center gap-4 border-b border-border pb-6 mb-8">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-primary/20 bg-primary/10 text-primary">
              <FileText className="h-6 w-6" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight text-foreground">
                Terms of Service
              </h1>
              <p className="text-xs text-muted-foreground mt-1">
                Platform Usage Agreement & Forensic Disclaimer
              </p>
            </div>
          </div>

          <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
            <section className="space-y-3">
              <h2 className="text-base font-semibold text-foreground flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-primary" />
                1. System Intent & Acceptable Use
              </h2>
              <p>
                The ScamSentry forensic platform is designed for legitimate URL
                threat scanning, academic research, and individual cybersecurity
                auditing. Any automated scraping, denial-of-service attempts, or
                reverse-engineering scans targeting our detection nodes is
                strictly prohibited.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-foreground flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-primary" />
                2. Advisory Threat Reports
              </h2>
              <p>
                All calculated threat levels, risk tags, and security
                classifications generated by the platform are advisory forensic
                indications. ScamSentry does not claim absolute liability for the
                structural safety of validated links. Final access discretion
                rests with the end user.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-foreground flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-primary" />
                3. Source Integrity & Credits
              </h2>
              <p>
                ScamSentry is an open-source initiative. Contributions and custom
                threat intelligence telemetry are compiled under developer
                governance. All modifications must adhere to the project&apos;s
                repository rules.
              </p>
            </section>
          </div>

          <div className="border-t border-border pt-6 mt-8 flex justify-between items-center">
            <span className="text-[10px] text-muted-foreground/40 font-medium">
              Last updated: June 2025
            </span>
            <Link href="/">
              <Button
                variant="outline"
                size="sm"
                className="text-xs font-semibold border-primary/20 hover:bg-primary/10 rounded-xl"
              >
                <ArrowLeft className="mr-2 h-3.5 w-3.5" />
                Back to Home
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
