"""add incidents and brand lockdowns tables

Revision ID: 3c66a50c7f99
Revises: 6d08021a9c9c
Create Date: 2026-06-07 13:30:32.027560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c66a50c7f99"
down_revision: Union[str, Sequence[str], None] = "6d08021a9c9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_brand_lockdowns",
        sa.Column("brand_name", sa.String(length=100), nullable=False),
        sa.Column("incident_title", sa.String(length=512), nullable=False),
        sa.Column("incident_link", sa.String(length=1024), nullable=False),
        sa.Column("reported_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("brand_name"),
    )
    op.create_table(
        "global_incidents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("link", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("is_highlight", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_global_incidents_link"), "global_incidents", ["link"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_global_incidents_link"), table_name="global_incidents")
    op.drop_table("global_incidents")
    op.drop_table("active_brand_lockdowns")
    # ### end Alembic commands ###
