"""Initial schema

Revision ID: 6d08021a9c9c
Revises:
Create Date: 2026-06-07 09:03:42.782909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d08021a9c9c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("threat_type", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("reported_at", sa.DateTime(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ledger_domain"), "ledger", ["domain"], unique=True)
    op.create_table(
        "scans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "complete", "error", name="scanstatus"),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum("safe", "suspicious", "dangerous", name="risklevel"),
            nullable=True,
        ),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scans_url"), "scans", ["url"], unique=False)
    op.create_table(
        "scan_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "layer", sa.Enum("L1", "L2", "L3", "L4", name="layername"), nullable=False
        ),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score_contribution", sa.Integer(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scan_results")
    op.drop_index(op.f("ix_scans_url"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_ledger_domain"), table_name="ledger")
    op.drop_table("ledger")
    # ### end Alembic commands ###
